__version__:
  serializer: 1
  data: 8
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 2.20241559856522
        Brightness: 1.8
        ExposureTime: 1677
        Gain: 1.07480485047226
    - Acquisition:
        Aperture: 7.32788514929765
        Brightness: 1.76704945160877
        ExposureTime: 1677
        Gain: 1
    - Acquisition:
        Aperture: 2
        Brightness: 1.79999999999998
        ExposureTime: 11739
        Gain: 1.78350591181766
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
      Experimental:
        ToneMapping:
          Enabled: always
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.3
          Removal:
            Enabled: no
            Threshold: 0.2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 10
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1
